version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: spot-hosting-db
    environment:
      POSTGRES_DB: spothostingDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spot-hosting-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spothostingDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - postgres

volumes:
  postgres_data:
